version: 2
jobs:
  build:
    docker:
      - image: python:2.7.12
        environment:
          FLASK_CONFIG: testing
      - image: selenium/standalone-chrome:3.1.0
      - image: redis
    working_directory: ~/tenki
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Install Dependencies
          command: make update-all
      - run:
          name: Run Tests
          command: make test

      - run:
          name: Run Tests
          command: make webtest
