version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    working_directory: ~/tenki
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Install Dependencies
          command: make update-all
      - run:
          name: Run Tests
          command: make test
      - run:
          name: docker compose
          command: docker-compose up -d
      - run:
          name: Run Web Tests
          command: make webtest
