version: 2
jobs:
  build:
    docker:
      - image: python:2.7.12
      - image: redis:3.0
    working_directory: ~/tenki
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make update-all
      - run:
          name: Run Tests
          command: make test
