version: 2
jobs:
  build:
    working_directory: ~/tenki
    docker:
      - image: python:2.7.12
        environment:
          FLASK_CONFIG: testing
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: make update-all
      - run:
        name: Run Tests
        command: make test
